---
title: Maak een lijst
hero_image: images / banner.png
description: Maak een nieuwe lijst
theme: rood
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: maker, ontwerp-0, programmeren-0, phys-comp-0, productie-0, community-0
interests: ""
technologies: "scratch"
site_areas: ""
steps:
  - 
    title: Maak een lijst
