---
title: Направите листу
hero_image: имагес / баннер.пнг
description: Направите нову листу
theme: црвена
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: творац, дизајн-0, програмирање-0, физ-цомп-0, производња-0, заједница-0
interests: ""
technologies: "огреботина"
site_areas:
steps:
  - 
    title: Направите листу
