---
title: Maak 'n lys
hero_image: images/banner.png
description: Maak 'n nuwe lys
theme: rooi
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skepper, ontwerp-0, programmering-0, fis-komp-0, vervaardiging-0, gemeenskap-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Maak 'n lys
