---
title: Fare un elenco
hero_image: images / banner.png
description: Crea una nuova lista
theme: rosso
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creatore, design-0, programmazione-0, compatta-0, fabbricazione-0, comunità-0
interests: ""
technologies: "graffiare"
site_areas: ""
steps:
  - 
    title: Fare un elenco
