---
title: Lav en liste
hero_image: images / banner.png
description: Lav en ny liste
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skaber, design-0, programmering-0, phys-comp-0, fremstilling-0, community-0
interests: ""
technologies: "kradse"
site_areas:
steps:
  - 
    title: Lav en liste
