---
title: Hacer una lista
hero_image: images / banner.png
description: Hacer una nueva lista
theme: rojo
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creador, dise침o-0, programaci칩n-0, phys-comp-0, fabricaci칩n-0, comunidad-0
interests: ""
technologies: "rasgu침o"
site_areas: ""
steps:
  - 
    title: Hacer una lista
