---
title: Membuat senarai
hero_image: imej / banner.png
description: Buat senarai baru
theme: merah
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: pencipta, reka bentuk-0, pengaturcaraan-0, phys-comp-0, pembuatan-0, komuniti-0
interests: ""
technologies: "awal"
site_areas:
steps:
  - 
    title: Membuat senarai
