---
title: Bir liste yap
hero_image: images / banner.png
description: Yeni bir liste yap
theme: kırmızı
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programlama-0, fiz-comp-0, production-0, topluluk-0
interests: ""
technologies: "çizik"
site_areas:
steps:
  - 
    title: Bir liste yap
